[background]
path = "/etc/greetd/wallpaper.png"
fit = "Cover"

[env]
XDG_CURRENT_DESKTOP = "sway"
XDG_SESSION_DESKTOP = "sway"
QT_QPA_PLATFORM = "wayland"
SDL_VIDEODRIVER = "wayland"
_JAVA_AWT_WM_NONREPARENTING = "1"

[GTK]
application_prefer_dark_theme = true
cursor_blink = true
font_name = "JetBrainsMono Nerd Font 14"
icon_theme_name = "Papirus-Dark"
theme_name = "Nordic"

[commands]
reboot = ["systemctl", "reboot"]
poweroff = ["systemctl", "poweroff"]
x11_prefix = ["startx", "/usr/bin/env"]

[appearance]
greeting_msg = "Welcome back"

[widget.clock]
format = "%H:%M"
resolution = "500ms"
label_width = 160
